### ISSUE TITLE
🐛 Bug Report: Total count of documents in collection does not update when document created from web SDK

### ISSUE THREAD

**Issue by NeonSpork** [appwrite/appwrite#2321]
### 👟 Reproduction steps

When using the Web SDK a frontend application create a document in a collection by using the method as outlined in the [documentation](https://appwrite.io/docs/client/database?sdk=web-default#databaseCreateDocument):
```typescript
appwrite.database.createDocument('collection_id', {})
```
Wherein the `{}` is shorthand for the object one wishes to create, which am assuming the user is structuring correctly as per the rules they created in the document collection.  
 
In the documentation it states that `read` and `write` permissions are optional, however I have found that if `read` is **_omitted_** it results in some unintended behavior.  

_It should be noted that in my document collection read permissions are specified as a rule, but there is no way to set the read/write parameters as required or not in the console._

There are other issues pertaining to documents and collections in general, but in all of the issues currently labeled with `bug` none of the relevant issues mentioned this problem specifically, so I chose to open a new issue.

### 👍 Expected behavior

The documents total number should update despite the fact that the optional parameter is left blank, OR the documentation and method should be updated such that read parameters are required.

### 👎 Actual Behavior

When using the method `.createDocument()` _without_ specifying read permissions, the actual list of documents **is** updated and a new document is created (increasing the `sum` parameter on the payload Promise<> delivered by `.listDocuments()`), however the console does not reflect the change in sum and does not update its totals in the browser.

This can be _rectified_ by specifying any read permissions, such as `['*']` for example, or `user:$id` etc. When the read parameters are specified the total updates. The total _also_ updates if the document is created from within the browser based console.

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Running appwrite locally in docker desktop, built without errors, and all containers running without errors.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I believe this is because the documents are fetched as the admin user who's logged in so only the data that user has access to is returned.

**Comment by TheMardy** [comment]
Indeed, with a fresh install of 0.11 only the documents with "role:member" or "*" are added to the total document count on the dashboard. But wouldn't it make the document statistic totally useless?

**Comment by stnguyen90** [comment]
Yes, I think it's a bug that needs to be corrected.

**Comment by stnguyen90** [comment]
Looks like this should be [fixed with the db refactor](https://github.com/appwrite/appwrite/blob/0b934c5e1dc52267eb31277c8251c0d93d496d05/app/controllers/api/projects.php#L291-L325).

**Comment by stnguyen90** [comment]
@TorstenDittmann, would it make sense to add this issue to the [DB Refactor project](https://github.com/appwrite/appwrite/projects/13)?

**Comment by joelmagoun** [comment]
![screenshot](https://i.imgur.com/fdO5Y4A.png)

Just a note that I see this also with the connection activity.  At the moment I am only using the rest API to interact with this instance, and see no connection activity and no documents.  

At the time of this screenshot, the database has about 80K documents, and has constant interaction.

**Comment by stnguyen90** [comment]
I believe connections is realtime connections. Do you have any of those?

**Comment by eldadfux** [comment]
Connections refer to connections only. In this branch we have changed the way we display the data. We aggregate the data in the background for better performance, and it will take it a few minutes to update. @lohanidamodar could share more.

**Comment by stnguyen90** [comment]
This is still a problem in 0.12. It doesn't seem like it's a permission problem fetching the stats anymore. The stats don't appear to exist in the database (new and old projects):

```
MariaDB [appwrite]> select * from _project_new_stats where metric = 'database.documents.count';
Empty set (0.001 sec)
```

**Comment by eldadfux** [comment]
@lohanidamodar any idea why this usage error might happen?

**Comment by chuiizeet** [comment]
![Screen Shot 2022-02-18 at 16 52 24](https://user-images.githubusercontent.com/23518097/154772743-07bb0b43-258a-4fe2-9140-aaa2363ae95f.png)

Since i upgrade to 0.12.x the documents count in console show 0.
All documents were created using python SDK.

**Comment by eldadfux** [comment]
Could be related to a problem we're trying to solve here: #2808
Can anyone confirm if their usage container is working while getting this problem?

**Comment by lohanidamodar** [comment]
> This is still a problem in 0.12. It doesn't seem like it's a permission problem fetching the stats anymore. The stats don't appear to exist in the database (new and old projects):
> 
> ```
> MariaDB [appwrite]> select * from _project_new_stats where metric = 'database.documents.count';
> Empty set (0.001 sec)
> ```
> 
> And I'm not sure if it's related, but I see the following in my appwrite-usage logs:
> 
> ```
> appwrite-usage  | Failed to save database counters data for project collections: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._project_6104f1a3cffa3_6195a09ba1adc' doesn't exist
> appwrite-usage  | [PDO] MySQL connection restarted
> appwrite-usage  | Failed to save database counters data for project collections: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._project_6106fbdd245c4_610710f221588' doesn't exist
> appwrite-usage  | [PDO] MySQL connection restarted
> appwrite-usage  | Failed to save database counters data for project collections: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._project_617395d51e291_6173976d98333' doesn't exist
> appwrite-usage  | [PDO] MySQL connection restarted
> appwrite-usage  | Failed to save database counters data for project collections: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appwrite._project_new_c1' doesn't exist
> ```

Found and fixed this issue, was error with collection table naming

**Comment by eldadfux** [comment]
This fix will be released as part of Appwrite 0.13

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻

**Comment by yngwi** [comment]
Hi,
I'm using a fresh in stall of version 0.13.2 and I still see this error. Even though documents are created just fine, the number of documents stays 0 even for documents created using the Appwrite admin backend.

**Comment by stnguyen90** [comment]
I'm on 0.13.4 and I still see this.

**Comment by stnguyen90** [comment]
@TorstenDittmann , can this be reopened and addressed?
