### ISSUE TITLE
🐛 Bug Report: Dart runtime 2.14 does not showing in the dropdown.

### ISSUE THREAD

**Issue by arieffajargemilang** [appwrite/appwrite#2455]
### 👟 Reproduction steps

i wanna create function using dart, but i cant fine dart runtime.

what I have done : 

- pull dart runtime
`
docker pull appwrite/runtime-for-dart:2.14
`

- add dart to .env
`
_APP_FUNCTIONS_RUNTIMES=node-16.0,php-8.0,python-3.9,ruby-3.0,java-16.0,dart-2.14
`
`
_APP_FUNCTIONS_ENVS=node-16.0,php-7.4,python-3.9,ruby-3.0,java-16.0,dart-2.14`

- run docker compose [from this doc](https://appwrite.io/docs/functions)
`
docker-compose up -d --remove-orphans
`
- and this is what i got
<img width="664" alt="Screen Shot 2021-12-01 at 14 52 14" src="https://user-images.githubusercontent.com/53034733/144195078-fc29a797-45b0-40f2-9e1d-66988c2120ba.png">

sorry if my english is so bad.
thanks.

### 👍 Expected behavior

can choice dart for create function

### 👎 Actual Behavior

dart runtime not found.

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Silfalion** [comment]
Encountering the same problem, r yu on mac m1 by any chance?

**Comment by tananga** [comment]
Why dart is not available by default?

**Comment by Silfalion** [comment]
I'm not sure in your case. But if you do have an arm based mac it's possible it's because of the php runtime restricting dart 2.14 like pointed out here:

https://github.com/appwrite/appwrite/issues/2457

**Comment by arieffajargemilang** [comment]
> Encountering the same problem, r yu on mac m1 by any chance?

i use 2 OS.. ubuntu server and macos (macbook pro 2017). i got same isue..

**Comment by arieffajargemilang** [comment]
> Why dart is not available by default?

only on appwrite version 0.11..

**Comment by arieffajargemilang** [comment]
> I'm not sure in your case. But if you do have an arm based mac it's possible it's because of the php runtime restricting dart 2.14 like pointed out here:
> 
> #2457

so, do i need to remove PHP?

**Comment by Silfalion** [comment]
I don't know what the problem could be but can you try running  docker-compose exec logs appwrite-worker-functions in the terminal.

**Comment by eldadfux** [comment]
@lohanidamodar now with the built-in support, can we list Dart as a default environment?

**Comment by arieffajargemilang** [comment]
but if i downgrade appwrite version to 0.10, dart runtime is available..

**Comment by lohanidamodar** [comment]
> @lohanidamodar now with the built-in support, can we list Dart as a default environment?

Seems we are yet to release dart env with the ARM support to php-runtimes and Appwrite. So may be we can have a patch release and make it available by default

**Comment by lohanidamodar** [comment]
@arieffajargemilang Hi, thank you for reporting the issue, however I'm unable to reproduce. I am running a digitalocean droplet with Ubuntu server 20.04 and dart 2.14 is properly showing up as the functions environment.
Please try to restart the server stack properly once the environment variable is properly set. Or try with fresh installation and let us know if you can successfully reproduce again.

**Comment by stnguyen90** [comment]
> but if i downgrade appwrite version to 0.10, dart runtime is available..

I'm pretty sure `dart-2.14` isn't available in Appwrite 0.10.4 because Appwrite 0.10.4 uses php-runtimes 0.4.0 and 2.14 isn't in 0.4.0.

**Comment by r-dev-limited** [comment]
I dont see it on last version ,with M1

**Comment by stnguyen90** [comment]
> I dont see it on last version ,with M1

Do you have `_APP_FUNCTIONS_ENVS` in your `.env` file? If so, remove it. Finally, make sure the dart version you want is in `_APP_FUNCTIONS_RUNTIMES`.

**Comment by stnguyen90** [comment]
@arieffajargemilang, are you still having problems with this or can this be closed now?

**Comment by stnguyen90** [comment]
Closing as this should be resolved now.

FYI, Appwrite version 0.15.3 uses appwrite/php-runtimes version [0.10.0](https://github.com/appwrite/appwrite/blob/0.15.3/composer.lock#L117-L123) and appwrite/php-runtimes version 0.10.0 has support for [dart versions 2.12 - 2.17](https://github.com/appwrite/runtimes/blob/0.10.0/src/Runtimes/Runtimes.php#L55-L60).

**Comment by Panth977** [comment]
so i found [one click droplet](https://marketplace.digitalocean.com/apps/appwrite), i had went through the whole process 
but i don't see the dart run time in cloud functions 
<img width="1728" alt="Screenshot 2023-01-28 at 12 05 11 PM" src="https://user-images.githubusercontent.com/75557781/215305748-4d3a8000-2d98-44db-aeb9-50007f65b9f0.png">
I have mac book M1 max chip, i have also created a local instance of appwrite, it as well don't have dart as runtime.
```
appwrite -v
1.1.1
```
Am i using outdated versions ? if so then how exactly do i get latest version ?
Or is dart removed as runtime ??

**Comment by XxThunderBlastxX** [comment]
> > @lohanidamodar now with the built-in support, can we list Dart as a default environment?
> 
> Seems we are yet to release dart env with the ARM support to php-runtimes and Appwrite. So may be we can have a patch release and make it available by default

I am running appwrite on my windows machine still cant get dart runtime :( .

**Comment by WilliamCunhaCardoso** [comment]
Where I can see such sopport per appwrite version? I am trying to use dart-3.0 in appwrite 1.4.2 and cannot have it
