### ISSUE TITLE
🐛 Bug Report: unable to change function timeout

### ISSUE THREAD

**Issue by BarFoo** [appwrite/appwrite#2657]
### 👟 Reproduction steps

- Change _APP_FUNCTIONS_TIMEOUT to a value above 900
- Restart apprewrite with `docker-compose up -d`
- Go into dashboard and update the value to something above 900
- Update/save the changes

### 👍 Expected behavior

Support a value above 900 seconds

### 👎 Actual Behavior

 Get validation error that the value must be between 1 and 900

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Should be addressed as part of https://github.com/appwrite/appwrite/pull/2659

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻

**Comment by PSJMcNeill** [comment]
I'm running into this issue on 0.13.

I update my .env file and update to _APP_FUNCTIONS_TIMEOUT.

then run docker-compose up -d

Everything recreates but Console still shows 900, when I check the .env file it's still set correctly as:
_APP_FUNCTIONS_TIMEOUT=1800

**Comment by stnguyen90** [comment]
> I'm running into this issue on 0.13.
> 
> I update my .env file and update to _APP_FUNCTIONS_TIMEOUT.
> 
> then run docker-compose up -d
> 
> Everything recreates but Console still shows 900, when I check the .env file it's still set correctly as: _APP_FUNCTIONS_TIMEOUT=1800

What exactly still shows 900? Maybe you need to clear your cache?

**Comment by shibakar** [comment]
> > I'm running into this issue on 0.13.
> > I update my .env file and update to _APP_FUNCTIONS_TIMEOUT.
> > then run docker-compose up -d
> > Everything recreates but Console still shows 900, when I check the .env file it's still set correctly as: _APP_FUNCTIONS_TIMEOUT=1800
> 
> What exactly still shows 900? Maybe you need to clear your cache?

yes value set at _APP_FUNCTIONS_TIMEOUT does not reflect and the filed cant be set more than 900 too
