### ISSUE TITLE
🚀 Feature: Allow Searching with Wildcard

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/appwrite#2676]
### 🔖 Feature description

It seems 0.12 has changed the search behavior such that it is no longer possible to search with a string prefix like `subst*` to match `substring`.

### 🎤 Pitch

One use case this would provide is implementing a sort of auto complete.

Some other users on discord have also asked about this including s3pp0, godfather, 0xchuy, and guille.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
I guess the main issue here is with the search mode we use. Looks like in the new DB we only support boolean mode, while natural language might be a better default. @TorstenDittmann @kodumbeats any implications to switching the default mode?

**Comment by mcchin** [comment]
I am looking forward to search with wildcard as well
Is a breaking changes for me when upgraded to `0.12.1`

I am using it to search for article title, it doesn't make sense for users to search every time with 100% match

**Comment by superseby2** [comment]
Same here. I intend to use the search query for an autocomplete input field. Using seach would bring only entries when a word matches completely
Would be nice to be able to specify what kind of match we are after. For autocomplete a partial text searching using like for instance.

**Comment by superseby2** [comment]
I may be wrong but looking at https://github.com/utopia-php/database/blob/ecc143f2cfe16b23675407035c6b5375ba263285/src/Database/Adapter/MariaDB.php#L1085
it seems like we are already using natural language (default) and not boolean ?
If that's the case, an option to support an autocomplete feature, would be to be able to use the boolean mode and the "*" operator or when fetching not too much of rows maybe a simple "like" statement support would do?

**Comment by eldadfux** [comment]
Update: we'll work on this issue this week, hoping to release a fix by next version.

**Comment by superseby2** [comment]
Worth noting : currently when looking for a word like "CI/CD" (which is avalaible in my collection), I am retrieving no result at all as if it doesn't like special characters like '/'

**Comment by pspierce** [comment]
Any update or thoughts on this one?

**Comment by superseby2** [comment]
It seems like its already implemented in Utopia -> https://github.com/utopia-php/database/releases/tag/0.15.0
I guess now it is a matter of bundling it with appwrite. (my 2 cents)

**Comment by TorstenDittmann** [comment]
We are just waiting for the release ;)

**Comment by mcchin** [comment]
Not trying to make this issue convoluted, will the next release for this also changes how `indexes` works?
For example, if I have a collection with the following attributes: `title`, `subtitle`, `author`, currently I need to have all index combinations:
- index title, if I need to query with `title`
- index title + subtitle, if I need to query with `title`, `subtitle`
- index subtitle + author, if I need to query with `subtitle `, `author`
- index title + subtitle + author, if I need to query with `title`, `subtitle`, `author`
and so on...

**Comment by TorstenDittmann** [comment]
> 



> Not trying to make this issue convoluted, will the next release for this also changes how `indexes` works? For example, if I have a collection with the following attributes: `title`, `subtitle`, `author`, currently I need to have all index combinations:
> 
> * index title, if I need to query with `title`
> * index title + subtitle, if I need to query with `title`, `subtitle`
> * index subtitle + author, if I need to query with `subtitle `, `author`
> * index title + subtitle + author, if I need to query with `title`, `subtitle`, `author`
>   and so on...
> 
> Will the next release makes the above less repetitive/complicated? Or I am missing something?

Do you mind creating a dedicated issue for this? 😄  Will be easier to track 👍🏻

**Comment by stnguyen90** [comment]
> > Not trying to make this issue convoluted, will the next release for this also changes how `indexes` works? For example, if I have a collection with the following attributes: `title`, `subtitle`, `author`, currently I need to have all index combinations:
> > 
> > * index title, if I need to query with `title`
> > * index title + subtitle, if I need to query with `title`, `subtitle`
> > * index subtitle + author, if I need to query with `subtitle `, `author`
> > * index title + subtitle + author, if I need to query with `title`, `subtitle`, `author`
> >   and so on...
> > 
> > Will the next release makes the above less repetitive/complicated? Or I am missing something?
> 
> Do you mind creating a dedicated issue for this? 😄 Will be easier to track 👍🏻

FYI I started a discussion about this: https://github.com/appwrite/appwrite/discussions/2720#discussioncomment-2077290

**Comment by TorstenDittmann** [comment]
We just released 0.13 and this should be fixed 👍🏻 

You can find the announcement [here](https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf).

Thank you a lot for reporting this 🙏🏻

**Comment by superseby2** [comment]
> Worth noting : currently when looking for a word like "CI/CD" (which is avalaible in my collection), I am retrieving no result at all as if it doesn't like special characters like '/'

@TorstenDittmann I am still having issues when trying to search a collection where I have documents with special characters in it, like "/" or "*", or '-'

ie : if in my collection I have the word "CID/CD"  searching  .search("ci") brings nothing.

**Comment by superseby2** [comment]
Never mind @TorstenDittmann I realized the problem comes from how fulltext works :) : CI/CD is treated as "CI" "/" and "CD" but "/" bing too small, it is ignored. 

I ended up with a trick where I use words without punctuation as index and it works well for my use case. 
For those interested, read : https://stackoverflow.com/questions/7120403/mysql-boolean-mode-fulltext-search-with-wildcards-and-literals

**Comment by superseby2** [comment]
Well actually  ..I am still facing an issue. 

Let's say I am typing "C++" -> I will not be able to retrieve any suggestions because "++" are punctuation and even with the trick to convert strings containing punctuation, I won't be able to have a match as "C" is too small to be included in MySQL fulltext index. 

- One way to solve this would be to allow us to change the min word length of MySQL (not sure about the implication of a length of 1 ...;) 
- Another way is to be able to have multiple search mode : the fulltext would be the default but we could decicde to use "like" for intance when it makes sense for us. 

Shoud I open aother issue ?

thx
