### ISSUE TITLE
🐛 Bug Report: Adding enums with length greater than before results in server error

### ISSUE THREAD

**Issue by nimit2801** [appwrite/appwrite#5595]
### 👟 Reproduction steps

Make a collection in a database for and an Enum Attribute
`paymentStatus` Attrib has
- 3 Enums: `Success` - `Pending` -  `Failure`
- if I edit this attribute and add `Intiated` this won't work, because `mariaDB` has already taken the highest length of `Pending`, `Success` and `Failure` that is 7

### 👍 Expected behavior

It should just add new data to the enum without an error

### 👎 Actual Behavior

This is the error it throws in the `Appwrite container logs`
![image](https://github.com/appwrite/appwrite/assets/53462249/6ceb0db3-1b27-41f7-9a48-738301fcbb95)

This is the error it throws on Client or on server while trying to add `Initiated` Enum to the attribute field

![image](https://github.com/appwrite/appwrite/assets/53462249/15c3249a-3764-4f6b-8059-41be1b58f13c)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by fliitor** [comment]
i can reproduce. Set varchar(50) (or text..) on enum fields ?

**Comment by joeyouss** [comment]
Hi @nimit2801 , is this fixed? If not, can you let me know?

**Comment by nimit2801** [comment]
> Hi @nimit2801 , is this fixed? If not, can you let me know?

Will have to check on the newer versions but according to my discussion with @stnguyen90 he said to post this issue for future reference ig. The solution was still not found.

**Comment by joeyouss** [comment]
Let me know if you check for newer versions

**Comment by fliitor** [comment]
It's because of [this code](https://github.com/appwrite/appwrite/blob/9f2bf844c7acc4932ca377941061665cd9b96645/app/controllers/api/databases.php#L1208)

Possibilities

1. Fixed size (255 for ex)
2. Round up to 25 more
3. Add `size` input on form to let user decide

**Comment by safwanyp** [comment]
Can I work on this 👀

**Comment by joeyouss** [comment]
Sure @safwanyp 

The approach we want to take with issue as of now would be the fixed size one as stated by @fliitor : ) Assigned the issue to you.

**Comment by safwanyp** [comment]
> Sure @safwanyp 
> 
> The approach we want to take with issue as of now would be the fixed size one as stated by @fliitor : ) Assigned the issue to you.

Sounds good! I'll have a PR ready soon 😁

**Comment by safwanyp** [comment]
Hey everyone, I've been trying to reproduce this bug on the console and CLI (v1.3.8), and even on the `master` branch of the repo, with 0 success. So it looks like this issue is fixed?

**Comment by Emilien-Lambert** [comment]
Hello, no the problem is not solved, I am on version `1.3.8` and I have exactly this problem. 

```
[Error] Timestamp: 2023-08-19T15:07:05+00:00
[Error] Method: POST
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
[Error] Type: PDOException
[Error] Message: Data too long for column 'type_de_recherche' at row 1
[Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
[Error] Line: 64
```

**Comment by safwanyp** [comment]
> Hello, no the problem is not solved, I am on version `1.3.8` and I have exactly this problem. 
> 
> ```
> [Error] Timestamp: 2023-08-19T15:07:05+00:00
> [Error] Method: POST
> [Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
> [Error] Type: PDOException
> [Error] Message: Data too long for column 'type_de_recherche' at row 1
> [Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
> [Error] Line: 64
> ```

Hey can you please tell me how you produced this error? I'm trying to replicate it on my end 😅

**Comment by Emilien-Lambert** [comment]
OK, I understand the problem.

For your information, this problem seems to occur when I use relationship in my collections. Without any relationship I couldn't reproduce the error. 

Now when I create an enum attribute and enter a first value, for example "fooo", in the mariaDB database the field is created with a varchar(4), because my first value was 4 characters long. If another choice in the enum is longer than 4, for example "lorem ipsum", then it exceeds varchar(4) and the error occurs.

**Comment by safwanyp** [comment]
> OK, I understand the problem.
> 
> For your information, this problem seems to occur when I use relationship in my collections. Without any relationship I couldn't reproduce the error. 
> 
> Now when I create an enum attribute and enter a first value, for example "fooo", in the mariaDB database the field is created with a varchar(4), because my first value was 4 characters long. If another choice in the enum is longer than 4, for example "lorem ipsum", then it exceeds varchar(4) and the error occurs. 
> 
> For information, relationships seem to be at the root of several problems at the moment, see :
> [issue #5481](https://github.com/appwrite/appwrite/issues/5481#issuecomment-1684895857) and  [issue #5850](https://github.com/appwrite/appwrite/issues/5850)

Yes, relationships being in beta have some issues. I'll try to reproduce it with a relation just to be sure!

**Comment by dcowan-london** [comment]
I can reproduce this with no relationships:
* Create a new collection
* Add one enum attribute with one element and save
* Edit the enum and add another attribute. Save
* Try to create a new document

I'm on 1.3.8

**Comment by safwanyp** [comment]
> Try to create a new document with the newly create element

Seems like this is where the issue is actually visible. I did not try doing this, so makes sense why I missed it. I'll try to reproduce it again on my end and push a PR!

CC: @dcowan-london

**Comment by mattie-cmsp** [comment]
I'm having this issue as well, on AppWrite 1.4.1

To be clear, the error doesn't occur when adding a new Enum to the attribute list.  The error occurs when adding a document that uses that Enum.

It seems to work like this:

1. Attribute is added to collection with a set of options: ex. "Four", "Five", "Six"
2. Appwrite creates a column in the table under _#_database_#_collection_## with the longest length in the list, "Four" and "Five" are 4 characters, so we get a 4 character column.
3. We go add an extra option "Seven"
4. Appwrite accepts this, but makes no changes to the column in the table.  At this point, Appwrite should update _#_database_#_collection_## setting the width of the column to 5 characters, but doesn't.
5. We add a document to the collection, including our new Enum option "Seven".  This causes Appwrite to throw the error.

Example error produced in appwrite error log for version 1.4.1:
```
[Error] Timestamp: 2023-10-22T06:38:10+00:00
[Error] Method: POST
[Error] URL: /v1/databases/:databaseId/collections/:collectionId/documents
[Error] Type: PDOException
[Error] Message: Data too long for column 'status' at row 1
[Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
[Error] Line: 62
```

Note the most useful part of this error, the message; "Data too long for column 'status' at row 1", isn't returned in the API response, thought the stack trace is.  I'm not including any error message related to where a code resolution would be, as the code that needs resolved is the part that handles updating of the attribute, and doesn't throw any error.

**Comment by sierra-hotel** [comment]
@mattie-cmsp hit the nail on the head.

This leads to a pretty cursed solution which is to create every enum with a value like `_________really_really_really_long_enum_column_name_________`  and then immediately delete it.

**Comment by t0mm4rx** [comment]
Still an issue on 1.4.12.
Enum values: `size_available`, `price_available`

Logs when trying to create a doc with `{type: 'price_available'}`:
```
[Error] Type: PDOException
[Error] Message: Data too long for column 'type' at row 1
[Error] File: @swoole-src/library/core/Database/PDOStatementProxy.php
[Error] Line: 62
```

**Comment by one-juru** [comment]
I updated my Appwrite instance after having this bug today. 
Even though your changelog states the issue was fixed with version 1.4.13, I still encounter the same issue. I updated the instance normally and did the migration as described in your documentation. Is there anything else I can do on my end?

**Comment by christyjacob4** [comment]
@one-juru @t0mm4rx Have you run the migration after upgrading to 1.4.13? The migration is required for existing attributes to be fixed.

**Comment by one-juru** [comment]
@christyjacob4 Thank you for the reply :)

Yes, I've updated as described by the Appwrite documentation, including executing the migration command and verifying that it did finish.

I didn't update from the previous version but instead skipped a few smaller updates. However I didn't skip any minor or major versions, so according to the docs this shouldn't cause any problems.

Is there anything that I could provide that would help to debug this issue?

**Comment by Emilien-Lambert** [comment]
Yes, for me too, I'm in v1.4.13, and I regularly have to manually change the size of my enums in the database.
