### ISSUE TITLE
🐛 Bug Report: 500 Error Accessing Disabled Collection

### ISSUE THREAD

**Issue by Lexazan** [appwrite/appwrite#5680]
### 👟 Reproduction steps

If collection is disabled via UI in Database->Some collection->Settings-> Enabled toggle
it can't be open using UI menus anymore, you will get an error 500
![image](https://github.com/appwrite/appwrite/assets/2877709/44698cb8-a7a9-4830-bd71-8cd1dc29b54d)
(AppwriteException: Collection with the requested ID could not be found.)
But you can still access the settings if you type in the collection settings url directly, E.g:
![image](https://github.com/appwrite/appwrite/assets/2877709/e96cc1ce-bf02-44b3-8a5e-acd9125afbff)

Seems like that's happening because Documents page of the collection is restricted when it is disabled.

### 👍 Expected behavior

It should be possible to open it, even when disabled.

### 👎 Actual Behavior

Throws error 500

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Version 1.3.6, Docker

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @Lexazan , did you try running it again? is it working fine now for you?

**Comment by joeyouss** [comment]
Hi @Lexazan I think this should be working now, can you please confirm once?

**Comment by Lexazan** [comment]
Hey, sorry guys, I am on vacation and can't check it now. Maybe someone else can?

**Comment by stnguyen90** [comment]
I still see the error on 1.3.8

![image](https://github.com/appwrite/appwrite/assets/1477010/ddc8f24d-3509-43e4-9b02-4b5822ee17a1)

but not on cloud.

**Comment by abnegate** [comment]
Closing as fixed in 1.4.0
