### ISSUE TITLE
Google oAuth |redirect_uri_mismatch|

### ISSUE THREAD

**Issue by eeqdevv** [appwrite/appwrite#5806]
I self hosting the appwrite then when use google oAuth shows **redirect_uri_mismatch status code :400**.
how i solf this problem ?
used flutter sdk as client side
<img width="373" alt="Screenshot 2023-07-12 at 10 54 07 AM" src="https://github.com/soodoku/tuber/assets/44582949/4b4aecc7-353b-4392-a9fa-835bcebc52db">

dependencies: appwrite: ^8.1.0

**Comment by stnguyen90** [comment]
@eeqdevv, what's the URL of the page when you're on that Google error page?

**Comment by eeqdevv** [comment]
> @eeqdevv, what's the URL of the page when you're on that Google error page?


thank you for replying. i fixed.  just appwrite provided not correct redirect url .just change https to http it works but other problem happen when production. i don't know why the https nor working on my side (the the redirect url)

**Comment by stnguyen90** [comment]
> i don't know why the https nor working on my side

@eeqdevv, if you have a reverse proxy in front of Appwrite, you need to make sure to make that connection between your reverse proxy and Appwrite HTTPS rather than HTTP. If you're still having trouble, please join us on [Discord](https://appwrite.io/discord).

For now, I'm going to close this as resolved.

**Comment by mauricioandre10-ctrl** [comment]
Still experiencing this issue in 2026 with a self-hosted Appwrite instance deployed using the **EasyPanel template**.

Even though the public endpoint is served over HTTPS, Appwrite generates the Google OAuth callback `redirect_uri` using **HTTP instead of HTTPS**, which causes Google to reject the login with `Error 400: redirect_uri_mismatch`.

**Details:**
- Appwrite deployed via EasyPanel template (self-hosted)
- Public endpoint: `https://backend.tecno.com`
- Generated `redirect_uri`: `http://backend.tecno.com/v1/account/sessions/oauth2/callback/google/<project-id>`
- Expected: `https://backend.tecno.com/v1/account/sessions/oauth2/callback/google/<project-id>`

The issue seems to be that Appwrite does not correctly detect the request scheme when running behind EasyPanel's reverse proxy, causing it to build the OAuth callback URL with HTTP instead of HTTPS.

Is there a supported environment variable or configuration to force Appwrite to use HTTPS when building OAuth callback URLs behind a reverse proxy? The variable `_APP_OPTIONS_TRUST_PROXY=true` does not appear to be documented or effective.

This makes the EasyPanel template setup unreliable for Google OAuth out of the box.
