### ISSUE TITLE
SMTP Error 0.6.2.125

### ISSUE THREAD

**Issue by thesmartrenovation** [appwrite/appwrite#880]
## 🐛 Bug Report

Hello, 

I have a clean install of Appwrite on version 0.6.2.125.

I follow the E-mail configuration guide: https://appwrite.io/docs/email-delivery

If I configure the external server the emails never arrive. I thought it was my mail server, but I tried to use Sendgrid and it doesn't work either.

**Comment by Hrdtr** [comment]
Hi, you can test your email smtp server using tool like https://www.gmass.co/smtp-test before. To make sure the the configuration and creds working

**Comment by thesmartrenovation** [comment]
> Hi, you can test your email smtp server using tool like https://www.gmass.co/smtp-test before. To make sure the the configuration and creds working

Yes, i tested my settings with that tool, and everything fine. 

I did a clean install on my VPS with a clean Centos 7 with no services, just docker and AppWrite and the mail service does not work, the native service and the external service, neither of them work.

**Comment by eldadfux** [comment]
@thesmartrenovation Sendgrid + Appwrite integration should work. Please share how your docker-compose.yml looks like (hide any secrets***). You can also use Appwrite dev mode to get more verbose error from the server HTTP response that might help detect the issue in your setup. More about it here: https://appwrite.io/docs/debugging under "Dev Mode"

**Comment by thesmartrenovation** [comment]
> @thesmartrenovation Sendgrid + Appwrite integration should work. Please share how your docker-compose.yml looks like (hide any secrets***). You can also use Appwrite dev mode to get more verbose error from the server HTTP response that might help detect the issue in your setup. More about it here: https://appwrite.io/docs/debugging under "Dev Mode"

Hi, 

This is my docker file:
```

version: '3'

services:
    traefik:
        image: traefik:v2.1.4
        command:
            - --providers.file.directory=/storage/config
            - --providers.file.watch=true
            - --providers.docker=true
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - appwrite-config:/storage/config:ro
            - appwrite-certificates:/storage/certificates:ro
        depends_on:
            - appwrite
        networks:
            - gateway
            - appwrite
    
    appwrite:
        image: appwrite/appwrite:0.6.2
        restart: unless-stopped
        networks:
            - appwrite
        labels:
            - traefik.http.routers.appwrite.rule=PathPrefix(`/`)
            - traefik.http.routers.appwrite-secure.rule=PathPrefix(`/`)
            - traefik.http.routers.appwrite-secure.tls=true
        volumes:
            - appwrite-uploads:/storage/uploads:rw
            - appwrite-cache:/storage/cache:rw
            - appwrite-config:/storage/config:rw
            - appwrite-certificates:/storage/certificates:rw
        depends_on:
            - mariadb
            - redis
            - smtp
            - clamav
            - influxdb
            - telegraf
        environment:
            - _APP_ENV=development
            - _APP_OPENSSL_KEY_V1={mykey}
            - _APP_DOMAIN={mydoamin}
            - _APP_DOMAIN_TARGET={mydomain}
            - _APP_REDIS_HOST=redis
            - _APP_REDIS_PORT=6379
            - _APP_DB_HOST=mariadb
            - _APP_DB_PORT=3306
            - _APP_DB_SCHEMA=appwrite
            - _APP_DB_USER=user
            - _APP_DB_PASS=password
            - _APP_INFLUXDB_HOST=influxdb
            - _APP_INFLUXDB_PORT=8086
            - _APP_STATSD_HOST=telegraf
            - _APP_STATSD_PORT=8125
            - _APP_OPTIONS_ABUSE=disabled
            - _APP_OPTIONS_FORCE_HTTPS=enabled
            - _APP_CONSOLE_WHITELIST_EMAILS={myemail}
            - _APP_SMTP_HOST={myhost}
            - _APP_SMTP_PORT=587
            - _APP_SMTP_SECURE=tls
            - _APP_SMTP_USERNAME={myusername}
            - _APP_SMTP_PASSWORD={mypassword}

    mariadb:
        image: appwrite/mariadb:1.0.3
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-mariadb:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=rootsecretpassword
            - MYSQL_DATABASE=appwrite
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        command: 'mysqld --innodb-flush-method=fsync'

    smtp:
        image: appwrite/smtp:1.0.1
        restart: unless-stopped
        networks:
            - appwrite
        environment:
            - MAILNAME=appwrite
            - RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16

    redis:
        image: redis:5.0
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-redis:/data:rw

    clamav:
        image: appwrite/clamav:1.0.9
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-uploads:/storage/uploads

    influxdb:
        image: influxdb:1.6
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-influxdb:/var/lib/influxdb:rw

    telegraf:
        image: appwrite/telegraf:1.0.0
        restart: unless-stopped
        networks:
            - appwrite

networks:
    gateway:
    appwrite:

volumes:
    appwrite-mariadb:
    appwrite-redis:
    appwrite-cache:
    appwrite-uploads:
    appwrite-certificates:
    appwrite-influxdb:
    appwrite-config:

```
If I disable my own SMTP it does not work with the native SMTP either.

**Comment by eldadfux** [comment]
Best shot here is by getting the verbose HTTP 500 error payload, without it we can only try and guess.

**Comment by thesmartrenovation** [comment]
> Best shot here is by getting the verbose HTTP 500 error payload, without it we can only try and guess.

see, I tried to test the mail function with the password recovery page

With the default SMTP it seems to work fine.

![image](https://user-images.githubusercontent.com/57076657/107082019-928d1280-67c1-11eb-8c0a-352855fc75bc.png)

But, the email never arrives at its destination.

With the external SMTP:

![image](https://user-images.githubusercontent.com/57076657/107083140-34f9c580-67c3-11eb-85b8-138b65ff10de.png)

No errors in the console, and the page does nothing.

**Comment by thesmartrenovation** [comment]
Is there any known problem in Centos 7? to reinstall the vps with Ubuntu or is there any guide to install version 0.7.0?

To confirm if the problem is the version of appwrite

**Comment by thesmartrenovation** [comment]
> Best shot here is by getting the verbose HTTP 500 error payload, without it we can only try and guess.

this is an error 500:

![image](https://user-images.githubusercontent.com/57076657/107084627-4a6fef00-67c5-11eb-909c-9c2151ac04a5.png)

**Comment by eldadfux** [comment]
@thesmartrenovation this might be related: https://discord.com/channels/564160730845151244/564161373148414012/713982513277567087

Solved by verifying the sender email on Sendgrid. Let me know if it helps

**Comment by thesmartrenovation** [comment]
> @thesmartrenovation this might be related: https://discord.com/channels/564160730845151244/564161373148414012/713982513277567087
> 
> Solved by verifying the sender email on Sendgrid. Let me know if it helps

My Sendgrid account is correctly verified. I have tested the configuration with https://www.gmass.co/ and everything works fine.

But, with the same configuration in appwrite it still does not work.

**Comment by thesmartrenovation** [comment]
Ok, if someone has the same problem, it is necessary to confirm that the VPS has the SMTP port enabled to send emails from the backend.

Also, it is necessary to write in the Appwrite variables the address from where the mail will be sent, since the relay services verify the identity of the mailbox that will send the mail. 

In this way:

```
- _APP_ENV=development
- _APP_SYSTEM_EMAIL_NAME={you company name}
- _APP_SYSTEM_EMAIL_ADDRESS={you company email}
```
I don't know if this information can be written in the mail delivery guide.
